import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from "react";

export default function Home({ Login, error }) {
    {/*Local Details*/}
    const [details, setDetails] = useState({username:"", password:""});
    const submitHandler = e => {
        e.preventDefault();
        Login(details);
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <form onSubmit={submitHandler}>
                    <div className={styles.main}>
                        {/* Wrapper */}
                        <div className="bg-white rounded-xl shadow-2xl flex-col w-1/4 max-w-md py-6 px-12 relative w-full flex justify-center">
                            {/* Anmelden Section */}
                            <div className="p-8 text-3xl text-indigo-600 font-semibold mb-2 group relative w-full flex justify-center">Anmelden</div>

                            {/* Input Felder */}
                            <div className="flex flex-col items-center pl-6 pr-6">
                                <div className="bg-white mb-4 pb-4 group w-full flex-col justify-center">
                                    {/* Error */}
                                    {(error != "") ? (
                                        <div className="rounded-md bg-red-50 p-4 mb-3">
                                            <div className="flex">
                                                <div className="flex-shrink-0">
                                                    <svg className="h-5 w-5 text-red-400"
                                                         xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                                                         fill="currentColor" aria-hidden="true">
                                                        <path fill-rule="evenodd"
                                                              d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                                                              clip-rule="evenodd"/>
                                                    </svg>
                                                </div>
                                                <div className="ml-3">
                                                    <h3 className="text-sm font-medium text-red-800">Nutzername oder Passwort falsch!</h3>
                                                </div>
                                            </div>
                                        </div>
                                    ) : ""}
                                    {/* Nutzername Feld */}
                                    <label htmlFor="description" className="block text-xs font-medium text-indigo-900">Nutzername</label>
                                    <div className="mt-1 relative rounded-xl text-black pb-4">
                                        <input type="text" name="username" id="username"
                                               onChange={e => setDetails({...details, username: e.target.value})} value={details.username}
                                               className="bg-white focus:border-indigo-500 block w-full py-2 px-4 sm:text-sm rounded-md border-2 border-indigo-900 outline-none"
                                               placeholder="" />
                                    </div>

                                    {/* Passwort Feld */}
                                    <label htmlFor="description" className="block text-xs font-medium text-indigo-900">Passwort</label>
                                    <div className="mt-1 relative rounded-xl shadow-sm text-black">
                                        <input type="password" name="password" id="password"
                                               onChange={e => setDetails({...details, password: e.target.value})} value={details.password}
                                               className="bg-white focus:border-indigo-500 block w-full py-2 px-4 sm:text-sm rounded-md border-2 border-indigo-900 outline-none"
                                               placeholder="" />
                                    </div>

                                    {/* Checkbox und Passwort vergessen */}
                                    <div className="flex mb-2 mt-5 justify-between items-center text-center content-center">
                                        <div className="flex place-items-center">
                                                <input id="candidates" aria-describedby="candidates-description"
                                                       name="candidates" type="checkbox"
                                                       className="focus:ring-indigo-500 h-3 w-3 text-indigo-600 border-gray-300 rounded hover:cursor-pointer" />
                                            <div className="ml-3 text-xs">
                                                <label htmlFor="candidates" className="font-semibold text-gray-700">Daten merken</label>
                                            </div>
                                        </div>
                                        <a href="#" className="text-xs focus:text-indigo-600">Passwort vergessen?</a>
                                    </div>
                                </div>
                            </div>

                            {/* Anmelden Button */}
                            <div className="mb-12 pl-6 pr-6">
                                <button type="submit" className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 hover:shadow-md focus: focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                    Anmelden
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </main>
        </div>
    )
}
